/**
 * Badge Parameters Configuration
 * Single source of truth for all badge parameters
 * Used by both backend (Zod validation) and frontend (UI generation)
 */
export default {
  title: {
    type: 'string',
    default: '',
    description: 'Badge title text displayed at the top',
    label: 'Title',
    placeholder: 'Enter title',
  },
  avatarSize: {
    type: 'number',
    default: 50,
    min: 30,
    max: 200,
    description: 'Avatar size in pixels',
    label: 'Avatar Size',
    placeholder: '80',
  },
  perRow: {
    type: 'number',
    default: 8,
    min: 1,
    max: 50,
    description: 'Number of avatars to display per row',
    label: 'Per Row',
    placeholder: 'Number per row',
  },
  shape: {
    type: 'enum',
    values: ['square', 'circle', 'squircle'],
    default: 'square',
    description: 'Shape of the avatar images',
    label: 'Shape',
    placeholder: 'circle, square, or squircle',
  },
  hideLabel: {
    type: 'boolean',
    default: false,
    description: 'Hide the username labels below avatars',
    label: 'Hide Label',
    placeholder: 'true or false',
  },
  fontSize: {
    type: 'number',
    default: 12,
    min: 10,
    max: 32,
    description: 'Font size for username labels in pixels',
    label: 'Font Size',
    placeholder: '16',
  },
  fontFamily: {
    type: 'string',
    default: "'Mona Sans', 'Open Sans', Verdana, Arial, sans-serif",
    description: 'Font family for text',
    label: 'Font Family',
    placeholder: 'e.g., Arial',
  },
  textColor: {
    type: 'string',
    default: '333333',
    description: 'Text color as hex code (without #)',
    label: 'Text Color',
    placeholder: 'e.g., black, #333',
  },
  backgroundColor: {
    type: 'string',
    default: 'transparent',
    description: 'Background color as hex code or CSS color name',
    label: 'Background Color',
    placeholder: 'e.g., white, #fff',
  },
  limit: {
    type: 'number',
    default: 96,
    min: 1,
    max: 500,
    description: 'Maximum number of users to display',
    label: 'Limit',
    placeholder: 'Limit number displayed',
  },
  outerBorderWidth: {
    type: 'number',
    default: 0,
    min: 0,
    max: 20,
    description: 'Width of outer border in pixels',
    label: 'Outer Border Width',
    placeholder: '0',
  },
  outerBorderColor: {
    type: 'string',
    default: '',
    description: 'Outer border color as hex code or CSS color name',
    label: 'Outer Border Color',
    placeholder: 'e.g., #000',
  },
  outerBorderRadius: {
    type: 'number',
    default: 0,
    min: 0,
    max: 50,
    description: 'Outer border radius in pixels',
    label: 'Outer Border Radius',
    placeholder: '0',
  },
  margin: {
    type: 'number',
    default: 20,
    min: 0,
    max: 100,
    description: 'Margin/spacing between avatars in pixels',
    label: 'Margin',
    placeholder: '35',
  },
  textOffset: {
    type: 'number',
    default: 20,
    min: 0,
    max: 100,
    description: 'Vertical offset for username text below avatar',
    label: 'Text Offset',
    placeholder: 'Offset for text',
  },
  svgWidth: {
    type: 'number',
    default: 0,
    min: 0,
    max: 5000,
    description: 'Custom SVG width in pixels (0 = auto)',
    label: 'SVG Width',
    placeholder: '0 for auto',
  },
  svgHeight: {
    type: 'number',
    default: 0,
    min: 0,
    max: 5000,
    description: 'Custom SVG height in pixels (0 = auto)',
    label: 'SVG Height',
    placeholder: '0 for auto',
  },
  footerText: {
    type: 'string',
    default: '',
    description: 'Footer text to display at bottom of badge',
    label: 'Footer Text',
    placeholder: 'Footer text',
  },
  dynamic: {
    type: 'boolean',
    default: false,
    description: 'Enable dynamic mode (renders in HTML instead of encoding images)',
    label: 'Dynamic Mode',
    placeholder: 'true or false',
  },
  isResponsive: {
    type: 'boolean',
    default: false,
    description: 'Make the badge responsive (scales with container)',
    label: 'Responsive',
    placeholder: 'true or false',
  },
  format: {
    type: 'enum',
    values: ['svg', 'png'],
    default: 'svg',
    description: 'Output image format (SVG or PNG)',
    label: 'Format',
    placeholder: 'svg or png',
  },
}
